# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\XMK1\AnacondaProjects\animals\main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 727)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 841, 711))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.MingQueAdd = QtWidgets.QPushButton(self.tab)
        self.MingQueAdd.setGeometry(QtCore.QRect(310, 60, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MingQueAdd.setFont(font)
        self.MingQueAdd.setObjectName("MingQueAdd")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(440, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(440, 80, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(440, 160, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(440, 240, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(440, 320, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(530, 590, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(40, 370, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(30, 320, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(40, 350, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.BMingQueAdd = QtWidgets.QPushButton(self.tab)
        self.BMingQueAdd.setGeometry(QtCore.QRect(300, 320, 75, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BMingQueAdd.setFont(font)
        self.BMingQueAdd.setObjectName("BMingQueAdd")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 270, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Calculate = QtWidgets.QPushButton(self.tab)
        self.Calculate.setGeometry(QtCore.QRect(10, 610, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Calculate.setFont(font)
        self.Calculate.setObjectName("Calculate")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(390, 10, 20, 631))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.MingQueRecord = QtWidgets.QListWidget(self.tab)
        self.MingQueRecord.setGeometry(QtCore.QRect(20, 130, 256, 121))
        self.MingQueRecord.setObjectName("MingQueRecord")
        self.BMingQueRecord = QtWidgets.QListWidget(self.tab)
        self.BMingQueRecord.setGeometry(QtCore.QRect(10, 470, 256, 121))
        self.BMingQueRecord.setObjectName("BMingQueRecord")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(50, 410, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 60, 135, 58))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MingQueTNT = QtWidgets.QLineEdit(self.layoutWidget)
        self.MingQueTNT.setObjectName("MingQueTNT")
        self.verticalLayout.addWidget(self.MingQueTNT)
        self.MingQueQuantity = QtWidgets.QLineEdit(self.layoutWidget)
        self.MingQueQuantity.setObjectName("MingQueQuantity")
        self.verticalLayout.addWidget(self.MingQueQuantity)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(100, 324, 135, 111))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.BMingQueDiameter = QtWidgets.QLineEdit(self.layoutWidget1)
        self.BMingQueDiameter.setText("")
        self.BMingQueDiameter.setObjectName("BMingQueDiameter")
        self.verticalLayout_2.addWidget(self.BMingQueDiameter)
        self.BMingQueLength = QtWidgets.QLineEdit(self.layoutWidget1)
        self.BMingQueLength.setText("")
        self.BMingQueLength.setObjectName("BMingQueLength")
        self.verticalLayout_2.addWidget(self.BMingQueLength)
        self.BMingQueHeadLength = QtWidgets.QLineEdit(self.layoutWidget1)
        self.BMingQueHeadLength.setText("")
        self.BMingQueHeadLength.setObjectName("BMingQueHeadLength")
        self.verticalLayout_2.addWidget(self.BMingQueHeadLength)
        self.BMingQueQuantity = QtWidgets.QLineEdit(self.layoutWidget1)
        self.BMingQueQuantity.setObjectName("BMingQueQuantity")
        self.verticalLayout_2.addWidget(self.BMingQueQuantity)
        self.MingQueClear = QtWidgets.QPushButton(self.tab)
        self.MingQueClear.setGeometry(QtCore.QRect(310, 160, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MingQueClear.setFont(font)
        self.MingQueClear.setObjectName("MingQueClear")
        self.BMingQueClear = QtWidgets.QPushButton(self.tab)
        self.BMingQueClear.setGeometry(QtCore.QRect(300, 510, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BMingQueClear.setFont(font)
        self.BMingQueClear.setObjectName("BMingQueClear")
        self.ResultTotal = QtWidgets.QLabel(self.tab)
        self.ResultTotal.setGeometry(QtCore.QRect(610, 80, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ResultTotal.setFont(font)
        self.ResultTotal.setText("")
        self.ResultTotal.setObjectName("ResultTotal")
        self.ResultTNT = QtWidgets.QLabel(self.tab)
        self.ResultTNT.setGeometry(QtCore.QRect(610, 160, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ResultTNT.setFont(font)
        self.ResultTNT.setText("")
        self.ResultTNT.setObjectName("ResultTNT")
        self.ResultBarrier = QtWidgets.QLabel(self.tab)
        self.ResultBarrier.setGeometry(QtCore.QRect(610, 250, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ResultBarrier.setFont(font)
        self.ResultBarrier.setText("")
        self.ResultBarrier.setObjectName("ResultBarrier")
        self.ResultAlert = QtWidgets.QLabel(self.tab)
        self.ResultAlert.setGeometry(QtCore.QRect(600, 330, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ResultAlert.setFont(font)
        self.ResultAlert.setText("")
        self.ResultAlert.setObjectName("ResultAlert")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(440, 410, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(440, 490, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.ResultHoleNumber = QtWidgets.QLabel(self.tab)
        self.ResultHoleNumber.setGeometry(QtCore.QRect(600, 420, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ResultHoleNumber.setFont(font)
        self.ResultHoleNumber.setText("")
        self.ResultHoleNumber.setObjectName("ResultHoleNumber")
        self.ResultHoleDangliang = QtWidgets.QLabel(self.tab)
        self.ResultHoleDangliang.setGeometry(QtCore.QRect(600, 500, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ResultHoleDangliang.setFont(font)
        self.ResultHoleDangliang.setText("")
        self.ResultHoleDangliang.setObjectName("ResultHoleDangliang")
        self.Export = QtWidgets.QPushButton(self.tab)
        self.Export.setGeometry(QtCore.QRect(210, 610, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Export.setFont(font)
        self.Export.setObjectName("Export")
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.MingQueAdd.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.BMingQueAdd.raise_()
        self.label_4.raise_()
        self.Calculate.raise_()
        self.line.raise_()
        self.MingQueRecord.raise_()
        self.BMingQueRecord.raise_()
        self.label_19.raise_()
        self.MingQueClear.raise_()
        self.BMingQueClear.raise_()
        self.ResultTotal.raise_()
        self.ResultTNT.raise_()
        self.ResultBarrier.raise_()
        self.ResultAlert.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.ResultHoleNumber.raise_()
        self.ResultHoleDangliang.raise_()
        self.Export.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.toolBox = QtWidgets.QToolBox(self.tab_2)
        self.toolBox.setGeometry(QtCore.QRect(20, 10, 801, 661))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 801, 553))
        self.page.setObjectName("page")
        self.Table1 = QtWidgets.QTableWidget(self.page)
        self.Table1.setGeometry(QtCore.QRect(30, 40, 301, 411))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Table1.setFont(font)
        self.Table1.setObjectName("Table1")
        self.Table1.setColumnCount(2)
        self.Table1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Table1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table1.setHorizontalHeaderItem(1, item)
        self.ThermoRemove = QtWidgets.QPushButton(self.page)
        self.ThermoRemove.setGeometry(QtCore.QRect(510, 210, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ThermoRemove.setFont(font)
        self.ThermoRemove.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ThermoRemove.setObjectName("ThermoRemove")
        self.ThermoAdd = QtWidgets.QPushButton(self.page)
        self.ThermoAdd.setGeometry(QtCore.QRect(500, 60, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ThermoAdd.setFont(font)
        self.ThermoAdd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ThermoAdd.setObjectName("ThermoAdd")
        self.ThermoSave = QtWidgets.QPushButton(self.page)
        self.ThermoSave.setGeometry(QtCore.QRect(510, 360, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ThermoSave.setFont(font)
        self.ThermoSave.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ThermoSave.setObjectName("ThermoSave")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 801, 553))
        self.page_2.setObjectName("page_2")
        self.Table2 = QtWidgets.QTableWidget(self.page_2)
        self.Table2.setGeometry(QtCore.QRect(10, 20, 641, 461))
        self.Table2.setObjectName("Table2")
        self.Table2.setColumnCount(6)
        self.Table2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Table2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table2.setHorizontalHeaderItem(5, item)
        self.AnimalRemove = QtWidgets.QPushButton(self.page_2)
        self.AnimalRemove.setGeometry(QtCore.QRect(670, 220, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.AnimalRemove.setFont(font)
        self.AnimalRemove.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AnimalRemove.setObjectName("AnimalRemove")
        self.AnimalAdd = QtWidgets.QPushButton(self.page_2)
        self.AnimalAdd.setGeometry(QtCore.QRect(670, 80, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.AnimalAdd.setFont(font)
        self.AnimalAdd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AnimalAdd.setObjectName("AnimalAdd")
        self.AnimalSave = QtWidgets.QPushButton(self.page_2)
        self.AnimalSave.setGeometry(QtCore.QRect(670, 360, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.AnimalSave.setFont(font)
        self.AnimalSave.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AnimalSave.setObjectName("AnimalSave")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 801, 553))
        self.page_3.setObjectName("page_3")
        self.Table3 = QtWidgets.QTableWidget(self.page_3)
        self.Table3.setGeometry(QtCore.QRect(10, 20, 641, 461))
        self.Table3.setObjectName("Table3")
        self.Table3.setColumnCount(6)
        self.Table3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Table3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table3.setHorizontalHeaderItem(5, item)
        self.SvvAdd = QtWidgets.QPushButton(self.page_3)
        self.SvvAdd.setGeometry(QtCore.QRect(690, 90, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SvvAdd.setFont(font)
        self.SvvAdd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SvvAdd.setObjectName("SvvAdd")
        self.SvvRemove = QtWidgets.QPushButton(self.page_3)
        self.SvvRemove.setGeometry(QtCore.QRect(690, 210, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SvvRemove.setFont(font)
        self.SvvRemove.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SvvRemove.setObjectName("SvvRemove")
        self.SvvSave = QtWidgets.QPushButton(self.page_3)
        self.SvvSave.setGeometry(QtCore.QRect(690, 320, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SvvSave.setFont(font)
        self.SvvSave.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SvvSave.setObjectName("SvvSave")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 801, 553))
        self.page_4.setObjectName("page_4")
        self.textEdit = QtWidgets.QTextEdit(self.page_4)
        self.textEdit.setGeometry(QtCore.QRect(480, 20, 281, 441))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(False)
        self.textEdit.setObjectName("textEdit")
        self.OtherSave = QtWidgets.QPushButton(self.page_4)
        self.OtherSave.setEnabled(False)
        self.OtherSave.setGeometry(QtCore.QRect(430, 480, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OtherSave.setFont(font)
        self.OtherSave.setObjectName("OtherSave")
        self.otherAddRec = QtWidgets.QPushButton(self.page_4)
        self.otherAddRec.setGeometry(QtCore.QRect(40, 480, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.otherAddRec.setFont(font)
        self.otherAddRec.setObjectName("otherAddRec")
        self.otherAddPic = QtWidgets.QPushButton(self.page_4)
        self.otherAddPic.setEnabled(False)
        self.otherAddPic.setGeometry(QtCore.QRect(230, 480, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.otherAddPic.setFont(font)
        self.otherAddPic.setObjectName("otherAddPic")
        self.otherPic = QtWidgets.QLabel(self.page_4)
        self.otherPic.setGeometry(QtCore.QRect(10, 150, 451, 311))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.otherPic.setFont(font)
        self.otherPic.setObjectName("otherPic")
        self.otherList = QtWidgets.QListWidget(self.page_4)
        self.otherList.setGeometry(QtCore.QRect(10, 20, 451, 111))
        self.otherList.setObjectName("otherList")
        self.OtherDelete = QtWidgets.QPushButton(self.page_4)
        self.OtherDelete.setEnabled(False)
        self.OtherDelete.setGeometry(QtCore.QRect(620, 480, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OtherDelete.setFont(font)
        self.OtherDelete.setObjectName("OtherDelete")
        self.toolBox.addItem(self.page_4, "")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "食物热量换算工具"))
        self.label.setText(_translate("MainWindow", "类型："))
        self.label_2.setText(_translate("MainWindow", " (kg)"))
        self.label_3.setText(_translate("MainWindow", "数量："))
        self.MingQueAdd.setText(_translate("MainWindow", "添加类型"))
        self.label_8.setText(_translate("MainWindow", "结果："))
        self.label_9.setText(_translate("MainWindow", "总量\n"
"（kg ）："))
        self.label_11.setText(_translate("MainWindow", "建议用量\n"
"（）："))
        self.label_12.setText(_translate("MainWindow", "距离\n"
"（g）："))
        self.label_13.setText(_translate("MainWindow", "距离1\n"
"（m）："))
        self.label_14.setText(_translate("MainWindow", "使用指南\n"
"详细操作方式见附录!!"))
        self.label_7.setText(_translate("MainWindow", "头长："))
        self.label_5.setText(_translate("MainWindow", "直径："))
        self.label_6.setText(_translate("MainWindow", "体长："))
        self.BMingQueAdd.setText(_translate("MainWindow", "添加类型"))
        self.label_4.setText(_translate("MainWindow", "不明确类型："))
        self.Calculate.setText(_translate("MainWindow", "计算"))
        self.label_19.setText(_translate("MainWindow", "数量："))
        self.MingQueClear.setText(_translate("MainWindow", "清除"))
        self.BMingQueClear.setText(_translate("MainWindow", "清除"))
        self.label_15.setText(_translate("MainWindow", "个数\n"
"（个）："))
        self.label_16.setText(_translate("MainWindow", "单个量\n"
"（kg）："))
        self.Export.setText(_translate("MainWindow", "导出历史纪录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "计算"))
        item = self.Table1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "名字"))
        item = self.Table1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "量"))
        self.ThermoRemove.setText(_translate("MainWindow", "删除"))
        self.ThermoAdd.setText(_translate("MainWindow", "新增"))
        self.ThermoSave.setText(_translate("MainWindow", "保存"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "换算"))
        item = self.Table2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "类型"))
        item = self.Table2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "部位"))
        item = self.Table2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "种量"))
        item = self.Table2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "热量"))
        item = self.Table2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "类别"))
        item = self.Table2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "备注"))
        self.AnimalRemove.setText(_translate("MainWindow", "删除"))
        self.AnimalAdd.setText(_translate("MainWindow", "新增"))
        self.AnimalSave.setText(_translate("MainWindow", "保存"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "常见食材"))
        item = self.Table3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "类型"))
        item = self.Table3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "部位"))
        item = self.Table3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "重量"))
        item = self.Table3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "使用量"))
        item = self.Table3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "热量种类"))
        item = self.Table3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "备注"))
        self.SvvAdd.setText(_translate("MainWindow", "新增"))
        self.SvvRemove.setText(_translate("MainWindow", "删除"))
        self.SvvSave.setText(_translate("MainWindow", "保存"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "使用表"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.OtherSave.setText(_translate("MainWindow", "保存文字"))
        self.otherAddRec.setText(_translate("MainWindow", "增加记录"))
        self.otherAddPic.setText(_translate("MainWindow", "添加/修改图片"))
        self.otherPic.setText(_translate("MainWindow", "(图片)"))
        self.OtherDelete.setText(_translate("MainWindow", "删除记录"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "其他"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "附录"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

